apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paperless-archivist
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - paperless-archivist.example.com
      secretName: paperless-archivist-tls
  rules:
    - host: paperless-archivist.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: paperless-archivist
                port:
                  name: http
