apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: paperless-archivist
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: paperless-archivist
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 8000
        - protocol: TCP
          port: 11434
        - protocol: TCP
          port: 443
