/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ready */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Prometheus metrics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Logged in */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/paperless-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Logged in through the optional Paperless login bridge */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/oidc/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OIDC login availability */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OidcConfigResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/oidc/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    return_to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to OIDC provider */
                307: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/oidc/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    code?: string;
                    state?: string;
                    error?: string;
                    error_description?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Login completed and session cookies issued */
                303: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current principal */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: password */
                        current_password: string;
                        /** Format: password */
                        new_password: string;
                    };
                };
            };
            responses: {
                /** @description Password changed and sessions revoked */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sessions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["Session"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sessions/{id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session revoked */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Runtime settings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RuntimeSettings"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateSettingsRequest"];
                };
            };
            responses: {
                /** @description Updated settings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RuntimeSettings"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/test-paperless": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paperless connection result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Notification webhook delivery test result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model-providers/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Provider connection result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model-providers/{name}/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Installed Ollama models for a configured provider */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OllamaInstalledModelsResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/secret-references": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Secret references */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Prompts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["Prompt"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        stage: components["schemas"]["Stage"];
                        name: string;
                        content: string;
                        output_schema?: unknown;
                        activate?: boolean;
                    };
                };
            };
            responses: {
                /** @description Created prompt */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Prompt usage summaries */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["PromptUsage"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts/{id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Prompt activated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TestPromptRequest"];
                };
            };
            responses: {
                /** @description Prompt test result with parsed output and validation errors */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TestPromptResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paperless/sync-metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sync summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaperlessSyncResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paperless/consistency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paperless metadata consistency report */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaperlessConsistencyResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paperless/completion-tags/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ReconcileCompletionTagsRequest"];
                };
            };
            responses: {
                /** @description Completion tag reconciliation plan or applied changes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReconcileCompletionTagsResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    range?: "24h" | "7d" | "30d" | "90d" | "12m" | "all";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dashboard counts and analytics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Live processing and lightweight debug status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardLiveStatus"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Usage, cost and pipeline-throughput analytics over a custom time range for the Statistics page. Defaults apply only when a parameter is absent or blank; a present-but-unparseable value is rejected with 400. */
        get: {
            parameters: {
                query?: {
                    /** @description Inclusive range start: an RFC3339 timestamp or a bare YYYY-MM-DD date (the day's first instant, UTC). Defaults to `to` minus 30 days. */
                    from?: string;
                    /** @description Exclusive range end: an RFC3339 timestamp or a bare YYYY-MM-DD date. A bare date means the END of that day (the next UTC midnight), so `from` and `to` naming the same day cover exactly that day. Defaults to now. */
                    to?: string;
                    /** @description Time-series bucket granularity. */
                    bucket?: "hour" | "day" | "week" | "month";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Statistics summary, zero-filled time series and breakdowns */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatisticsResponse"];
                    };
                };
                /** @description Unparseable from/to, from not before to, or unknown bucket */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/mode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateWorkflowModeRequest"];
                };
            };
            responses: {
                /** @description Updated runtime settings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RuntimeSettings"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/controls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateWorkflowControlsRequest"];
                };
            };
            responses: {
                /** @description Updated runtime settings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RuntimeSettings"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                    /** @description Inclusive lower bound on document_date (YYYY-MM-DD). A present but unparseable value is rejected with 400. */
                    date_from?: string;
                    /** @description Inclusive upper bound on document_date (YYYY-MM-DD). A present but unparseable value is rejected with 400. */
                    date_to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Inventory page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unparseable date_from/date_to filter */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/runtime-hints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live runtime hints for a provider (loaded model, VRAM, version) */
        get: {
            parameters: {
                query?: {
                    /** @description Provider name. Defaults to ai.default_provider. */
                    provider?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Hints (whether reachable or not is in the body) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AiRuntimeHints"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/{document_id}/metadata-trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diagnostic trace of the most recent metadata-stage run */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    document_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Trace found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MetadataTrace"];
                    };
                };
                /** @description No metadata run exists for this document */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Document chat sessions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["DocumentChatSession"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateDocumentChatSessionRequest"];
                };
            };
            responses: {
                /** @description Created document chat session */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            title: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Document chat messages */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["DocumentChatMessage"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/sessions/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PostDocumentChatMessageRequest"];
                };
            };
            responses: {
                /** @description Created user and assistant chat messages */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PostDocumentChatMessageResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{paperless_document_id}/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    paperless_document_id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        stages?: components["schemas"]["Stage"][];
                        mode?: components["schemas"]["ProcessingMode"];
                    };
                };
            };
            responses: {
                /** @description Created or reused run */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/ocr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Queued missing OCR jobs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/full": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Queued missing full pipeline jobs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    status?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Review queue */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Approved and applied */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        ids: string[];
                        /** @enum {string} */
                        decision: "approve" | "reject";
                    };
                };
            };
            responses: {
                /** @description Batch review result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Rejected */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{id}/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        patch: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            responses: {
                /** @description Edited and applied */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/recovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    older_than_seconds?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Stale lease and stuck run recovery candidates */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecoveryStatusResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/recovery/stale-leases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RecoveryRequest"];
                };
            };
            responses: {
                /** @description Requeued stale running jobs whose leases are older than the recovery window */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecoveryActionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/recovery/stuck-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RecoveryRequest"];
                };
            };
            responses: {
                /** @description Completed or failed active runs that no longer have active jobs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecoveryActionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Audit events */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Audit events as CSV */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/integrity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Audit hash-chain verification */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditIntegrityReport"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/retention/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Applied configured audit and AI artifact retention */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RetentionResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Users */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        username: string;
                        email?: string | null;
                        /** Format: password */
                        password: string;
                        roles: components["schemas"]["Role"][];
                    };
                };
            };
            responses: {
                /** @description Created user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Enabled user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Disabled user and revoked sessions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Rejected because this is the last enabled administrator */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        roles: components["schemas"]["Role"][];
                    };
                };
            };
            responses: {
                /** @description Updated user roles */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Rejected because this is the last enabled administrator */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: password */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Reset password and revoked sessions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/api-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description API tokens */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        expires_in_days?: number | null;
                        scopes: ("runs:read" | "runs:write" | "inventory:read" | "batches:write" | "chat:write" | "reviews:read" | "reviews:write" | "settings:read" | "settings:write" | "users:manage" | "audit:read")[];
                    };
                };
            };
            responses: {
                /** @description Created token */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/api-tokens/{id}/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        expires_in_days?: number | null;
                    };
                };
            };
            responses: {
                /** @description Rotated token */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/api-tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Revoked token */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Role: "viewer" | "reviewer" | "operator" | "admin" | "auditor";
        /** @enum {string} */
        Stage: "ocr" | "metadata" | "apply";
        /** @enum {string} */
        ProcessingMode: "manual_review" | "auto_select_review" | "full_auto";
        /** @enum {string} */
        AiProviderKind: "ollama" | "openai" | "anthropic" | "openai_compatible" | "mineru";
        AiProviderSettings: {
            name: string;
            kind: components["schemas"]["AiProviderKind"];
            base_url: string;
            default_text_model?: string | null;
            default_vision_model?: string | null;
            /** Format: double */
            cost_per_1m_input_tokens_usd?: number | null;
            /** Format: double */
            cost_per_1m_output_tokens_usd?: number | null;
            /** Format: uuid */
            secret_id?: string | null;
            enabled: boolean;
        };
        LoginRequest: {
            username: string;
            /** Format: password */
            password: string;
        };
        MeResponse: {
            username: string;
            roles: components["schemas"]["Role"][];
            permissions: components["schemas"]["PermissionFlags"];
            csrf_token?: string | null;
        };
        PermissionFlags: {
            read_dashboard: boolean;
            read_runs: boolean;
            write_runs: boolean;
            read_inventory: boolean;
            write_batches: boolean;
            use_chat: boolean;
            read_reviews: boolean;
            write_reviews: boolean;
            read_settings: boolean;
            write_settings: boolean;
            manage_users: boolean;
            read_audit: boolean;
        };
        OidcConfigResponse: {
            enabled: boolean;
            login_url?: string | null;
            provider?: string | null;
            paperless_login_enabled?: boolean;
        };
        RuntimeSettings: {
            [key: string]: unknown;
        };
        UpdateSettingsRequest: {
            settings: components["schemas"]["RuntimeSettings"];
            paperless_token?: string | null;
            notification_webhook_url?: string | null;
            provider_secrets?: {
                [key: string]: string;
            } | null;
        };
        OllamaInstalledModel: {
            name: string;
            parameter_size?: string | null;
            quantization_level?: string | null;
            /** Format: int64 */
            size_bytes?: number | null;
            /** Format: double */
            size_gb?: number | null;
            modified_at?: string | null;
            digest?: string | null;
        };
        OllamaInstalledModelsResponse: {
            provider: string;
            models: components["schemas"]["OllamaInstalledModel"][];
        };
        PaperlessSyncResponse: {
            archive?: string;
            /** @enum {string} */
            mode?: "full" | "full_initial" | "delta" | "full_after_delta_error";
            /** Format: date-time */
            delta_cursor?: string | null;
            synced_documents?: number;
        } & {
            [key: string]: unknown;
        };
        PaperlessConsistencyMismatch: {
            paperless_document_id: number;
            fields: string[];
        };
        PaperlessConsistencyResponse: {
            ok: boolean;
            documents_checked: number;
            missing_local: number[];
            stale_local: number[];
            mismatches: components["schemas"]["PaperlessConsistencyMismatch"][];
        };
        ReconcileCompletionTagsRequest: {
            /** @default true */
            dry_run: boolean;
            document_ids?: number[];
        };
        CompletionTagReconcilePlan: {
            paperless_document_id: number;
            add: string[];
        };
        ReconcileCompletionTagsResponse: {
            dry_run: boolean;
            planned: components["schemas"]["CompletionTagReconcilePlan"][];
            applied: number[];
        };
        BacklogCounts: {
            /** Format: int64 */
            total_documents: number;
            /** Format: int64 */
            complete: number;
            /** Format: int64 */
            missing_ocr: number;
            /** Format: int64 */
            waiting_review: number;
            /**
             * Format: int64
             * @description Documents whose ocr_status or metadata_status is 'failed'. The six per-field missing_* counters were removed with the fossil per-field status columns (migration 0039).
             */
            failed: number;
            /** Format: int64 */
            running: number;
            /** Format: int64 */
            never_processed: number;
        };
        DashboardRangeOption: {
            /** @enum {string} */
            key: "24h" | "7d" | "30d" | "90d" | "12m" | "all";
            label: string;
        };
        DashboardKpis: {
            /** Format: double */
            completion_rate: number;
            /** Format: int64 */
            open_backlog: number;
            /** Format: double */
            failure_rate: number;
            /** Format: int64 */
            review_load: number;
            /** Format: int64 */
            running_jobs: number;
            /** Format: int64 */
            throughput: number;
            /** Format: double */
            cost_in_range_usd: number | null;
            /** Format: double */
            mttc_seconds: number | null;
            /** Format: int64 */
            p95_stage_duration_ms: number | null;
        };
        DashboardComparison: {
            /** Format: int64 */
            jobs_created_delta: number;
            /** Format: int64 */
            jobs_succeeded_delta: number;
            /** Format: int64 */
            jobs_failed_delta: number;
            /** Format: int64 */
            open_backlog_delta: number;
        };
        DashboardStageStatus: {
            stage: string;
            /** Format: int64 */
            complete: number;
            /** Format: int64 */
            pending: number;
            /** Format: int64 */
            failed: number;
            /** Format: int64 */
            waiting_review: number;
            /** Format: int64 */
            running: number;
        };
        DashboardTimeBucket: {
            /** Format: date-time */
            bucket: string;
            label: string;
            /** Format: int64 */
            jobs_created: number;
            /** Format: int64 */
            jobs_succeeded: number;
            /** Format: int64 */
            jobs_failed: number;
            /** Format: int64 */
            runs_created: number;
            /** Format: int64 */
            runs_succeeded: number;
            /** Format: int64 */
            runs_failed: number;
        };
        DashboardBacklogPoint: {
            /** Format: date-time */
            bucket: string;
            label: string;
            /** Format: int64 */
            total_documents: number;
            /** Format: int64 */
            complete: number;
            /** Format: int64 */
            open_backlog: number;
            /** Format: int64 */
            failed: number;
            /** Format: int64 */
            waiting_review: number;
            /** Format: int64 */
            running: number;
        };
        DashboardStatusCount: {
            status: string;
            /** Format: int64 */
            count: number;
        };
        ProviderUsageStats: {
            provider: string;
            model: string;
            stage: string;
            /** Format: int64 */
            request_count: number;
            /** Format: double */
            avg_duration_ms: number;
            /** Format: int64 */
            p95_duration_ms: number;
            /** Format: int64 */
            input_tokens: number;
            /** Format: int64 */
            output_tokens: number;
            /** Format: double */
            estimated_cost_usd?: number | null;
            /** Format: int64 */
            feedback_count: number;
            /** Format: int64 */
            positive_feedback: number;
            /** Format: int64 */
            negative_feedback: number;
            /** Format: double */
            acceptance_rate: number | null;
            latency_history: (number | null)[];
        };
        QualityStats: {
            /** Format: int64 */
            review_decisions: number;
            /** Format: int64 */
            review_approved: number;
            /** Format: int64 */
            review_edited: number;
            /** Format: int64 */
            review_rejected: number;
            /** Format: double */
            acceptance_rate: number | null;
            /** Format: int64 */
            uncertainty_reviews: number;
            /** Format: int64 */
            validation_warning_reviews: number;
        };
        DashboardCostBucket: {
            /** Format: date-time */
            bucket: string;
            label: string;
            /** Format: double */
            cost_usd: number | null;
            /** Format: int64 */
            request_count: number;
            /** Format: int64 */
            input_tokens: number;
            /** Format: int64 */
            output_tokens: number;
        };
        DashboardProviderCostSummary: {
            provider: string;
            model: string;
            /** Format: double */
            cost_usd: number | null;
            /** Format: int64 */
            request_count: number;
            /** Format: int64 */
            input_tokens: number;
            /** Format: int64 */
            output_tokens: number;
            sparkline: (number | null)[];
        };
        DashboardStats: {
            /** Format: date-time */
            generated_at: string;
            /** @enum {string} */
            selected_range: "24h" | "7d" | "30d" | "90d" | "12m" | "all";
            available_ranges: components["schemas"]["DashboardRangeOption"][];
            kpis: components["schemas"]["DashboardKpis"];
            comparison: components["schemas"]["DashboardComparison"];
            stage_status: components["schemas"]["DashboardStageStatus"][];
            throughput_series: components["schemas"]["DashboardTimeBucket"][];
            backlog_series: components["schemas"]["DashboardBacklogPoint"][];
            job_status: components["schemas"]["DashboardStatusCount"][];
            run_status: components["schemas"]["DashboardStatusCount"][];
            review_status: components["schemas"]["DashboardStatusCount"][];
            provider_usage: components["schemas"]["ProviderUsageStats"][];
            quality: components["schemas"]["QualityStats"];
            cost_series: components["schemas"]["DashboardCostBucket"][];
            cost_breakdown_by_provider: components["schemas"]["DashboardProviderCostSummary"][];
        };
        ServiceProcessingStatus: {
            /** @enum {string} */
            state: "idle" | "running" | "error";
            title: string;
            description: string;
            /** Format: date-time */
            last_event_at?: string | null;
        };
        DashboardLiveRun: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            trace_id: string;
            paperless_document_id: number;
            mode: components["schemas"]["ProcessingMode"];
            status: string;
            trigger_tag: string;
            stages: components["schemas"]["Stage"][];
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        DashboardLiveJob: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            run_id: string;
            /** Format: uuid */
            trace_id: string;
            paperless_document_id: number;
            stage: components["schemas"]["Stage"];
            status: string;
            attempts: number;
            max_attempts: number;
            lease_owner?: string | null;
            /** Format: date-time */
            lease_until?: string | null;
            /** Format: date-time */
            updated_at: string;
            error_message?: string | null;
        };
        DashboardLiveLlmEvent: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            run_id: string;
            /** Format: uuid */
            job_id?: string | null;
            stage: components["schemas"]["Stage"];
            provider: string;
            model: string;
            duration_ms?: number | null;
            /** Format: date-time */
            created_at: string;
        };
        DashboardLiveFailure: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            run_id: string;
            paperless_document_id: number;
            stage: components["schemas"]["Stage"];
            status: string;
            /** @enum {string} */
            failure_kind: "failed" | "retry_scheduled" | "retry_ready";
            attempts: number;
            error_message: string;
            /** Format: date-time */
            next_attempt_at?: string | null;
            /** Format: date-time */
            updated_at: string;
        };
        NeedsAttentionItem: {
            kind: string;
            /** @enum {string} */
            severity: "info" | "warning" | "critical";
            title: string;
            description: string;
            action_key?: string | null;
            /** Format: int64 */
            count?: number | null;
        };
        DashboardLiveStatus: {
            /** Format: date-time */
            generated_at: string;
            workflow_mode: components["schemas"]["ProcessingMode"];
            autopilot_enabled: boolean;
            workflow_safety: components["schemas"]["WorkflowSafetyStatus"];
            selector: components["schemas"]["ServiceProcessingStatus"];
            /** Format: date-time */
            next_selector_scan_at?: string | null;
            llm: components["schemas"]["ServiceProcessingStatus"];
            paperless: components["schemas"]["ServiceProcessingStatus"];
            active_runs: components["schemas"]["DashboardLiveRun"][];
            active_jobs: components["schemas"]["DashboardLiveJob"][];
            recent_llm_events: components["schemas"]["DashboardLiveLlmEvent"][];
            recent_failures: components["schemas"]["DashboardLiveFailure"][];
            needs_attention: components["schemas"]["NeedsAttentionItem"][];
        };
        UpdateWorkflowModeRequest: {
            mode: components["schemas"]["ProcessingMode"];
        };
        WorkflowSafetyStatus: {
            paused: boolean;
            dry_run: boolean;
            hourly_document_limit?: number | null;
            daily_document_limit?: number | null;
            hourly_remaining?: number | null;
            daily_remaining?: number | null;
        };
        UpdateWorkflowControlsRequest: {
            paused?: boolean;
            dry_run?: boolean;
            hourly_document_limit?: number | null;
            daily_document_limit?: number | null;
        };
        WorkflowDebugContext: {
            selector_reason?: string | null;
            workflow_mode?: components["schemas"]["ProcessingMode"] | null;
            workflow_paused?: boolean | null;
            dry_run?: boolean | null;
            prompt_language?: string | null;
            tag_output_language?: string | null;
            detected_language?: string | null;
            /** Format: float */
            detected_language_confidence?: number | null;
            detected_language_source?: string | null;
            current_run_status?: string | null;
            last_error?: string | null;
            next_required_stage?: string | null;
        } & {
            [key: string]: unknown;
        };
        DashboardResponse: {
            counts: components["schemas"]["BacklogCounts"];
            stats: components["schemas"]["DashboardStats"];
        };
        StatisticsSummary: {
            /** Format: int64 */
            request_count: number;
            /** Format: int64 */
            input_tokens: number;
            /** Format: int64 */
            output_tokens: number;
            /** Format: double */
            avg_duration_ms?: number | null;
            /** Format: double */
            estimated_cost_usd?: number | null;
            /** Format: int64 */
            jobs_succeeded: number;
            /** Format: int64 */
            jobs_failed: number;
            /** Format: int64 */
            jobs_cancelled: number;
        };
        StatisticsTimePoint: {
            /** Format: date-time */
            bucket: string;
            /** Format: int64 */
            request_count: number;
            /** Format: int64 */
            input_tokens: number;
            /** Format: int64 */
            output_tokens: number;
            /** Format: double */
            avg_duration_ms?: number | null;
        };
        StatisticsThroughputPoint: {
            /** Format: date-time */
            bucket: string;
            /** Format: int64 */
            succeeded: number;
            /** Format: int64 */
            failed: number;
            /** Format: int64 */
            cancelled: number;
        };
        StatisticsBreakdownRow: {
            provider?: string;
            model?: string;
            stage?: string;
            /** Format: int64 */
            request_count: number;
            /** Format: int64 */
            input_tokens: number;
            /** Format: int64 */
            output_tokens: number;
            /** Format: double */
            avg_duration_ms?: number | null;
            /** Format: double */
            estimated_cost_usd?: number | null;
        };
        StatisticsResponse: {
            /** Format: date-time */
            from: string;
            /** Format: date-time */
            to: string;
            /** @enum {string} */
            bucket: "hour" | "day" | "week" | "month";
            summary: components["schemas"]["StatisticsSummary"];
            time_series: components["schemas"]["StatisticsTimePoint"][];
            throughput_series: components["schemas"]["StatisticsThroughputPoint"][];
            by_provider: components["schemas"]["StatisticsBreakdownRow"][];
            by_model: components["schemas"]["StatisticsBreakdownRow"][];
            by_stage: components["schemas"]["StatisticsBreakdownRow"][];
        };
        DocumentInventoryItem: {
            debug_context?: components["schemas"]["WorkflowDebugContext"] | null;
        } & {
            [key: string]: unknown;
        };
        StandardMetadataSuggestion: {
            /** @enum {string} */
            field?: "correspondent" | "document_type" | "document_date";
            suggested_name?: string | null;
            /** Format: date */
            suggested_date?: string | null;
            current_correspondent?: number | null;
            current_document_type?: number | null;
            current_date?: string | null;
            /** Format: float */
            confidence?: number | null;
            evidence?: string | null;
        } & {
            [key: string]: unknown;
        };
        DocumentPatch: {
            content?: string;
            title?: string;
            tags?: number[];
            correspondent?: number | null;
            document_type?: number | null;
            /** Format: date */
            created?: string;
            custom_fields?: unknown;
            standard_metadata?: components["schemas"]["StandardMetadataSuggestion"];
        };
        ReviewItem: {
            /** Format: uuid */
            id: string;
            paperless_document_id: number;
            stage: components["schemas"]["Stage"];
            status: string;
            suggested_patch: components["schemas"]["DocumentPatch"];
            edited_patch?: components["schemas"]["DocumentPatch"] | null;
            validation_warnings?: unknown;
            /** @description Patch field names whose Paperless values changed after review creation. */
            conflict_fields?: string[];
            /** Format: date-time */
            conflicted_at?: string | null;
            debug_context?: components["schemas"]["WorkflowDebugContext"] | null;
            /** @description Cached Paperless title from the document_inventory, surfaced so the review UI can show the actual document title instead of falling back to "Document {id}" when the suggested_patch has no title. */
            paperless_title?: string | null;
            /** Format: date-time */
            created_at: string;
        } & {
            [key: string]: unknown;
        };
        AuditEvent: {
            [key: string]: unknown;
        };
        AuditIntegrityReport: {
            ok: boolean;
            /** Format: int64 */
            checked_events: number;
            /** Format: int64 */
            legacy_events: number;
            latest_event_hash?: string | null;
            /** Format: uuid */
            broken_event_id?: string | null;
            broken_reason?: string | null;
        };
        RetentionResult: {
            /** Format: int64 */
            audit_events_deleted: number;
            /** Format: int64 */
            ai_artifacts_deleted: number;
            /** Format: int64 */
            ocr_page_cache_deleted: number;
            /**
             * Format: int64
             * @description Terminal pipeline runs pruned past runs_retention_days; their jobs and AI artifacts are deleted with them via CASCADE.
             */
            pipeline_runs_deleted: number;
        };
        RecoveryCandidate: {
            /** Format: uuid */
            run_id: string;
            /** Format: uuid */
            job_id?: string | null;
            paperless_document_id: number;
            stage?: components["schemas"]["Stage"] | null;
            status: string;
            lease_owner?: string | null;
            /** Format: date-time */
            lease_until?: string | null;
            /** Format: date-time */
            updated_at: string;
            reason: string;
        };
        RecoverySummary: {
            stale_leases_requeued: number;
            stuck_runs_failed: number;
            stuck_runs_completed: number;
        };
        RecoveryRequest: {
            older_than_seconds?: number;
        };
        RecoveryStatusResponse: {
            older_than_seconds: number;
            items: components["schemas"]["RecoveryCandidate"][];
        };
        RecoveryActionResponse: {
            older_than_seconds: number;
            summary: components["schemas"]["RecoverySummary"];
        };
        Prompt: {
            /** Format: uuid */
            id: string;
            stage: components["schemas"]["Stage"];
            name: string;
            version: number;
            content: string;
            output_schema?: unknown;
            active: boolean;
            /** Format: date-time */
            created_at: string;
        };
        PromptUsage: {
            /** Format: uuid */
            prompt_id: string;
            /** Format: int64 */
            run_count: number;
            /** Format: int64 */
            job_count: number;
            /** Format: date-time */
            last_used_at?: string | null;
            /** Format: double */
            avg_duration_ms: number;
            last_provider?: string | null;
            last_model?: string | null;
        };
        TestPromptRequest: {
            stage: components["schemas"]["Stage"];
            content: string;
            sample_text?: string | null;
            paperless_document_id?: number | null;
            provider_name?: string | null;
            model?: string | null;
        };
        TestPromptResponse: {
            provider: string;
            model: string;
            stage: components["schemas"]["Stage"];
            raw_text: string;
            parsed?: unknown;
            validation_errors: string[];
            warnings: string[];
            /** Format: int32 */
            duration_ms: number;
        };
        DocumentChatSource: {
            paperless_document_id: number;
            title?: string | null;
            snippet: string;
            /** Format: double */
            score: number;
            source_kind: string;
        };
        AiRuntimeHints: {
            provider: string;
            reachable: boolean;
            version?: string | null;
            loaded_models?: components["schemas"]["AiLoadedModel"][];
            num_parallel?: number | null;
            max_loaded_models?: number | null;
            keep_alive?: string | null;
            hint?: string | null;
        };
        AiLoadedModel: {
            name: string;
            /** Format: int64 */
            size_vram_bytes?: number | null;
            /** Format: date-time */
            last_used_at?: string | null;
        };
        MetadataTrace: {
            paperless_document_id: number;
            current_state: {
                title?: string | null;
                correspondent?: string | null;
                document_type?: string | null;
                document_date?: string | null;
                tags: string[];
            };
            latest_run: components["schemas"]["MetadataTraceRun"];
        };
        MetadataTraceRun: {
            /** Format: uuid */
            run_id: string;
            stage: string;
            status: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            applied_at?: string | null;
            model?: string | null;
            provider?: string | null;
            llm_suggestion?: {
                [key: string]: unknown;
            } | null;
            per_field_outcomes: components["schemas"]["MetadataFieldOutcome"][];
        };
        MetadataFieldOutcome: {
            /** @enum {string} */
            field: "title" | "correspondent" | "document_type" | "document_date" | "tags" | "fields";
            /** @enum {string} */
            outcome: "applied" | "review" | "skipped" | "dropped" | "rejected";
            value?: unknown;
            /** Format: float */
            confidence?: number | null;
            reason?: string | null;
            warnings: {
                [key: string]: unknown;
            }[];
        };
        DocumentChatSession: {
            /** Format: uuid */
            id: string;
            title: string;
            /** Format: uuid */
            created_by?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        DocumentChatMessage: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            session_id: string;
            /** @enum {string} */
            role: "user" | "assistant" | "system";
            content: string;
            provider?: string | null;
            model?: string | null;
            metadata?: unknown;
            sources: components["schemas"]["DocumentChatSource"][];
            /** Format: date-time */
            created_at: string;
        };
        CreateDocumentChatSessionRequest: {
            title?: string;
        };
        PostDocumentChatMessageRequest: {
            question: string;
            document_ids?: number[] | null;
            max_sources?: number;
        };
        PostDocumentChatMessageResponse: {
            /** Format: uuid */
            session_id: string;
            /** Format: uuid */
            user_message_id: string;
            /** Format: uuid */
            assistant_message_id: string;
            answer: string;
            sources: components["schemas"]["DocumentChatSource"][];
        };
        Session: {
            [key: string]: unknown;
        };
        User: {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
