- op: add
  path: /spec/template/spec/containers/0/env
  value:
    - name: ARCHIVIST_METRICS_TOKEN
      valueFrom:
        secretKeyRef:
          name: paperless-archivist-metrics
          key: ARCHIVIST_METRICS_TOKEN
