apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - servicemonitor.yaml
  - prometheusrule.yaml
patches:
  - path: deployment-api-metrics-env-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: paperless-archivist-api
